# Generated by Django 5.1.6 on 2025-03-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
    ]
