# Generated by Django 5.1.6 on 2025-03-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='review_videos/'),
        ),
    ]
