# Generated by Django 5.1.6 on 2025-03-12 18:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_image_review_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(choices=[(Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0')], decimal_places=1, max_digits=3),
        ),
    ]
