# Generated by Django 5.1.6 on 2025-03-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_review_verified_purchase_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='verified_purchase',
        ),
    ]
