# Generated by Django 5.1.5 on 2025-03-21 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0007_alter_review_rating"),
        ("review", "0008_remove_review_verified_purchase"),
    ]

    operations = []
