# Generated by Django 5.1.6 on 2025-03-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_product_name'),
        ('review', '0008_remove_review_verified_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vendor_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.product'),
        ),
    ]
