# Generated by Django 5.1.5 on 2025-03-27 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0028_keywordsearchhistory_synonymcache"),
        ("review", "0009_merge_20250321_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="ecommerce.product",
            ),
        ),
    ]
