# Generated by Django 5.1.6 on 2025-03-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_merge_20250321_1921'),
        ('review', '0009_merge_20250325_1212'),
    ]

    operations = [
    ]
