# Generated by Django 5.1.6 on 2025-03-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
