# Generated by Django 5.1.5 on 2025-03-30 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0010_alter_review_product"),
        ("review", "0010_vote"),
    ]

    operations = []
