# Generated by Django 5.1.6 on 2025-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_alter_review_product_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlike',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewlike',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
