# Generated by Django 5.1.6 on 2025-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_reviewlike_dislikes_reviewlike_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlike',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='reviewlike',
            name='likes',
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
