# Generated by Django 5.1.6 on 2025-03-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_vote'),
        ('review', '0013_remove_reviewlike_dislikes_remove_reviewlike_likes_and_more'),
    ]

    operations = [
    ]
