# Generated by Django 5.1.6 on 2025-03-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_merge_20250328_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.DeleteModel(
            name='ReviewLike',
        ),
    ]
