# Generated by Django 5.1.6 on 2025-03-31 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_merge_0010_alter_review_product_0010_vote'),
        ('review', '0015_remove_review_dislikes_remove_review_likes_and_more'),
    ]

    operations = [
    ]
