# Generated by Django 5.1.6 on 2025-04-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_merge_20250401_0310'),
        ('review', '0016_merge_20250331_1133'),
    ]

    operations = [
    ]
