# Generated by Django 5.1.6 on 2025-04-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_alter_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
    ]
