INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (1, 1, 'add_logentry', 'Can add log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (2, 1, 'change_logentry', 'Can change log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (3, 1, 'delete_logentry', 'Can delete log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (4, 1, 'view_logentry', 'Can view log entry');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (5, 2, 'add_permission', 'Can add permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (6, 2, 'change_permission', 'Can change permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (7, 2, 'delete_permission', 'Can delete permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (8, 2, 'view_permission', 'Can view permission');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (9, 3, 'add_group', 'Can add group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (10, 3, 'change_group', 'Can change group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (11, 3, 'delete_group', 'Can delete group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (12, 3, 'view_group', 'Can view group');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (13, 4, 'add_user', 'Can add user');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (14, 4, 'change_user', 'Can change user');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (15, 4, 'delete_user', 'Can delete user');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (16, 4, 'view_user', 'Can view user');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (17, 5, 'add_contenttype', 'Can add content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (18, 5, 'change_contenttype', 'Can change content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (19, 5, 'delete_contenttype', 'Can delete content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (20, 5, 'view_contenttype', 'Can view content type');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (21, 6, 'add_session', 'Can add session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (22, 6, 'change_session', 'Can change session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (23, 6, 'delete_session', 'Can delete session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (24, 6, 'view_session', 'Can view session');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (25, 7, 'add_product', 'Can add product');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (26, 7, 'change_product', 'Can change product');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (27, 7, 'delete_product', 'Can delete product');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (28, 7, 'view_product', 'Can view product');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (29, 8, 'add_productphoto', 'Can add product photo');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (30, 8, 'change_productphoto', 'Can change product photo');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (31, 8, 'delete_productphoto', 'Can delete product photo');
INSERT INTO "auth_permission" ("id", "content_type_id", "codename", "name") VALUES (32, 8, 'view_productphoto', 'Can view product photo');
