"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hb(f$n4rukc90(&#%nxq8hkg&yrqg0-@6nj42#==h3xu97v*g("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ecommerce",
    "user",
    "shoppingcart",
    "vendor",
    'review',
    "forums",
    'web',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR/'templates'], 
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.i18n',
                "ecommerce.context_processors.currency_context",  # ✅ 加在这里
            ],
        },
    },
]

WSGI_APPLICATION = "web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'
USE_L10N = True

LANGUAGES = [
    ('en', _('English')),
    ('ja', _('Japanese')),
    ('zh-hans', _('Simplified Chinese')),  # ✅ 确保 Django 识别 `zh-hans`
]

# 语言对应的货币符号与汇率（汇率以人民币为基准）
LANGUAGE_CURRENCY_MAP = {
    'en': {'symbol': '$', 'rate': 0.14},     # 美元
    'ja': {'symbol': '¥', 'rate': 20.0},     # 日元
    'zh-hans': {'symbol': '¥', 'rate': 1.0}, # 人民币
}


LANGUAGE_COOKIE_NAME = 'django_language'  
LANGUAGE_COOKIE_AGE = 86400

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),  # 翻译文件存储目录
]

TIME_ZONE = "Asia/Shanghai"
USE_TZ = True  # 启用时区支持

USE_I18N = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# 让 Django 识别项目中的静态文件目录
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 确保项目中的 static 目录可以被 Django 识别
]

# 让 Django 知道收集静态文件的最终存放目录
STATIC_ROOT = BASE_DIR / "staticfiles"

# 默认上传文件的存储路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


BASE_DIR = Path(__file__).resolve().parent.parent

# 媒体文件的 URL 前缀
MEDIA_URL = '/media/'
# 媒体文件在服务器上的存储路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
]

# Default weights for safety score calculation
MHI_WEIGHT = 25  # Material Hazard Index weight (%)
ACR_WEIGHT = 35  # Age Compliance Risk weight (%)
VHD_WEIGHT = 30  # Visual Hazard Detection weight (%)
ICS_WEIGHT = 10  # Information Completeness Score weight (%)