# Generated by Django 5.1.6 on 2025-03-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_comment_dislikes_comment_likes_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reports',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
