# Generated by Django 5.1.6 on 2025-04-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_comment_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedComment',
            fields=[
            ],
            options={
                'verbose_name': 'Reported Comment',
                'verbose_name_plural': 'Reported Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('forums.comment',),
        ),
    ]
