# Generated by Django 5.1.6 on 2025-04-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
