# Generated by Django 5.1.5 on 2025-01-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "t_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("t_name", models.CharField(max_length=255)),
                ("t_info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "p_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("p_name", models.CharField(max_length=255)),
                ("p_time", models.DateField()),
                ("p_image", models.ImageField(upload_to="product_images/")),
                ("p_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("p_state", models.CharField(max_length=50)),
                (
                    "t_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecommerce.type"
                    ),
                ),
            ],
        ),
    ]
