# Generated by Django 5.1.5 on 2025-01-22 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="t_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="p_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="p_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="p_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="p_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="p_state",
        ),
        migrations.RemoveField(
            model_name="product",
            name="p_time",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available."),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this product across whole shopping mall",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(default="Unnamed Product", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                default="enabled",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="thumbnail_image",
            field=models.URLField(default="https://via.placeholder.com/150"),
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                ("photo_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "photo_url",
                    models.URLField(default="https://via.placeholder.com/150"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="ecommerce.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
