# Generated by Django 5.1.6 on 2025-02-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_product_t_id_remove_product_p_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(default='https://via.placeholder.com/150', upload_to='product_thumbnails/'),
        ),
    ]
