# Generated by Django 5.1.6 on 2025-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_product_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('stock', 'Stock'), ('out_of_stock', 'Out of Stock')], default='stock', max_length=15),
        ),
    ]
