# Generated by Django 5.1.6 on 2025-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_product_stock_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="", max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=""),
        ),
    ]
