# Generated by Django 5.1.6 on 2025-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_product_status_product_max_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_age',
            field=models.PositiveIntegerField(default='', help_text='Maximum age suitable for the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_age',
            field=models.PositiveIntegerField(default='', help_text='Minimum age suitable for the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
