# Generated by Django 5.1.5 on 2025-02-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0010_alter_product_description_alter_product_max_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productphoto",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="productphoto",
            name="photo",
            field=models.ImageField(
                default="https://via.placeholder.com/150", upload_to="product_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="productphoto",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos_etc",
                to="ecommerce.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="product_videos/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="ecommerce.product",
                    ),
                ),
            ],
        ),
    ]
