# Generated by Django 5.1.5 on 2025-02-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0011_remove_productphoto_photo_url_productphoto_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productphoto",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="ecommerce.product",
            ),
        ),
    ]
