# Generated by Django 5.1.5 on 2025-02-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_product_description_en_product_description_es_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_zh_hans',
            new_name='description_zh',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name_zh_hans',
            new_name='product_name_zh',
        ),
    ]
