# Generated by Django 5.1.5 on 2025-02-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_rename_description_zh_product_description_zh_hans_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_zh_hans',
            new_name='description_zh_Hans',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name_zh_hans',
            new_name='product_name_zh_Hans',
        ),
    ]
