# Generated by Django 5.1.5 on 2025-02-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_product_description_zh_hans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_zh_Hans',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_zh_Hans',
        ),
    ]
