# Generated by Django 5.1.6 on 2025-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_remove_product_description_zh_hans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('tangible', 'Tangible'), ('virtual', 'Virtual')], default='tangible', max_length=10, verbose_name='Product Type'),
        ),
    ]
