# Generated by Django 5.1.5 on 2025-03-01 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0024_product_description_zh_hans_and_more"),
        ("ecommerce", "0024_product_product_type"),
    ]

    operations = []
