# Generated by Django 5.1.6 on 2025-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_merge_20250301_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=300, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_es',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_ja',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_ko',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_zh_hans',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(upload_to='product_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(upload_to='product_photos/'),
        ),
    ]
