# Generated by Django 5.1.6 on 2025-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_remove_product_name_product_materials_and_more'),
    ]

    operations = [
       # migrations.RemoveField(
        #    model_name='product',
        #    name='name',
        #),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of materials', max_length=255),
        ),
    ]
