# Generated by Django 5.1.6 on 2025-04-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_remove_product_name_product_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='safety_issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
