# Generated by Django 5.1.6 on 2025-04-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_alter_product_safety_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='safety_issues',
            field=models.TextField(default=list),
        ),
    ]
