# Generated by Django 5.1.6 on 2025-04-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_remove_product_name_product_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warnings',
            field=models.TextField(blank=True, default='', help_text='Warnings or safety notes related to the product'),
        ),
    ]
