<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-04-10 07:42
=======
# Generated by Django 5.1.6 on 2025-04-10 07:36
>>>>>>> origin/josh

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('ecommerce', '0031_alter_product_safety_issues'),
=======
        ('ecommerce', '0031_product_warnings'),
>>>>>>> origin/josh
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='safety_issues',
            field=models.JSONField(default=list),
        ),
    ]
