# Generated by Django 5.1.6 on 2025-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_product_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='safety_issues',
            field=models.JSONField(default=list),
        ),
    ]
