# Generated by Django 5.1.6 on 2025-04-11 02:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_alter_product_safety_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vhd_category_score',
            field=models.PositiveIntegerField(default=0, help_text='Category score from edge detection (1=Dull, 3=Medium, 5=Sharp)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vhd_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Visual Hazard Detection score', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product across the whole shopping mall', primary_key=True, serialize=False),
        ),
    ]
