# Generated by Django 5.1.6 on 2025-04-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_product_vhd_category_score_product_vhd_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vhd_category_score',
        ),
        migrations.AddField(
            model_name='product',
            name='sharpness_category_score',
            field=models.PositiveIntegerField(default=0, help_text='Sharpness category score (1=Dull, 3=Medium, 5=Sharp)'),
        ),
    ]
