# Generated by Django 5.1.6 on 2025-04-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_product_warnings'),
        ('ecommerce', '0034_remove_product_vhd_category_score_and_more'),
    ]

    operations = [
    ]
