# Generated by Django 5.1.6 on 2025-04-14 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_merge_20250414_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product across whole shopping mall', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_issues',
            field=models.JSONField(default=list),
        ),
    ]
