# Generated by Django 5.1.6 on 2025-02-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_order_customer_order_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('hold', 'Hold'), ('ticket-issued', 'Ticket Issued'), ('complete', 'Complete'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
