# Generated by Django 5.1.6 on 2025-02-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
