# Generated by Django 5.1.5 on 2025-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingcart", "0005_remove_order_created_at_remove_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ticket_issue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
