# Generated by Django 5.1.5 on 2025-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingcart", "0006_order_cancel_date_order_refund_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="complete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="hold_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pending_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
