# Generated by Django 5.1.5 on 2025-01-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "u_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("u_name", models.CharField(max_length=255)),
                ("u_password", models.CharField(max_length=255)),
                ("u_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("u_sex", models.CharField(blank=True, max_length=1, null=True)),
                ("u_status", models.CharField(max_length=255)),
                ("u_code", models.CharField(blank=True, max_length=255, null=True)),
                ("u_phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
